### ISSUE TITLE
Can't select text at all

### ISSUE THREAD

**Issue by Dan9er** [Fred-Barclay/Termination#65]
Atom: 1.19.3
Termination: 0.6.1
OS: Ubuntu 16.04

Using a custom theme:
```less
.termination .xterm {
  background-color: black;
  color: lime;

  ::selection {
    background-color: lime;
  }

  .terminal-cursor {
    background-color: lime;
  }
}
```

Absolutely can't select text in any way.
